### ISSUE TITLE
CircleCI does not know how to deploy this project.

### ISSUE THREAD

**Issue by joshua-rutherford** [DecipherNow/gm-fabric-jvm#19]
We need to add a circle.yml file with the following content:
```
machine:
    java:
        version: oraclejdk8

deployment:
    override:
        - if [ -z "${CI_PULL_REQUEST}" ]; then mvn deploy -P deploy -s settings.xml; fi
```
